In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 

warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop('species',axis = 1)
y = df['species']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42
)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [10]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [11]:
model_knn.score(X_test,y_test)

0.98

In [12]:
from sklearn.svm import SVC

In [13]:
model_svm = SVC(C=30,kernel='rbf',gamma= 'auto')

In [14]:
model_svm = SVC(gamma= 'auto')

In [15]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [16]:
model_svm.score(X_test,y_test)

1.0

# Now lets use the grid search CV

In [17]:
from sklearn.model_selection import GridSearchCV

In [18]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30,40],
    'kernel' :['rbf','linear'],
},cv = 5,return_train_score = False )

In [19]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30, 40], 'kernel': ['rbf', 'linear']})

In [20]:
classifier.cv_results_

{'mean_fit_time': array([0.00340519, 0.00330796, 0.00361962, 0.00271821, 0.0068439 ,
        0.00341563, 0.0036263 , 0.00628247, 0.00380325, 0.00285535]),
 'std_fit_time': array([0.00120555, 0.00140491, 0.00117267, 0.00089793, 0.0064717 ,
        0.00282977, 0.00188124, 0.00507103, 0.00068413, 0.00038635]),
 'mean_score_time': array([0.00267706, 0.00279641, 0.00239854, 0.00620289, 0.00139761,
        0.00139885, 0.00295115, 0.00266962, 0.0023046 , 0.00230474]),
 'std_score_time': array([0.00078397, 0.00074734, 0.00101907, 0.00990931, 0.00049232,
        0.00049053, 0.0017933 , 0.00084463, 0.00059394, 0.0006957 ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30, 40, 40],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 40, 'kernel': 'rbf'},
  {'C': 40, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        , 1.        , 1.        ]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667, 1.        ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       , 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      , 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979, 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7, 7, 7], dtype=int32)}

In [21]:
results = pd.DataFrame(classifier.cv_results_)

In [22]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003405,0.001206,0.002677,0.000784,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003308,0.001405,0.002796,0.000747,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003620,0.001173,0.002399,0.001019,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002718,0.000898,0.006203,0.009909,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.006844,0.006472,0.001398,0.000492,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003416,0.002830,0.001399,0.000491,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003626,0.001881,0.002951,0.001793,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.006282,0.005071,0.002670,0.000845,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,7
8,0.003803,0.000684,0.002305,0.000594,40,rbf,"{'C': 40, 'kernel': 'rbf'}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,7
9,0.002855,0.000386,0.002305,0.000696,40,linear,"{'C': 40, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,7

In [23]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000
8       40          rbf         0.960000
9       40       linear         0.960000

In [24]:
from sklearn.model_selection import RandomizedSearchCV

In [25]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30,40],
    'kernel' :['rbf','linear'],
},n_iter = 4, cv = 5,return_train_score = False )

In [26]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30, 40],
                                        'kernel': ['rbf', 'linear']})

In [27]:
results = pd.DataFrame(classifier_r.cv_results_)

In [28]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002735,0.001071,0.002402,0.001175,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002605,0.000495,0.001903,0.000192,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,3
2,0.002399,0.000489,0.002207,0.000397,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002606,0.000803,0.001810,0.000400,rbf,40,"{'kernel': 'rbf', 'C': 40}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,4

In [29]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1       10       linear         0.973333
2       10          rbf         0.980000
3       40          rbf         0.960000